### PR TITLE
Add ease-of-use changes to login and chat

### LINKED ISSUE #21: Hitting "Enter" in the password field should log in
As a user, when logging in, I want to hit "Enter" in the password field and have it automatically log in, as opposed to requiring a button click, so that I can log in more quickly.

### LINKED ISSUE #35: Hitting "Enter" in the chat box should send a message
This will likely have a solution similar to #21, but in this case, we also will likely want "Shift+Enter" to do a newline, per standard.

### PR DESCRIPTION
**Pull request by segeeslice**
## Overview

This PR adds a few details for clarity and better UX:

- **Login Screen**
    - Hitting "Enter" while typing the username shifts focus to password
    - Hitting "Enter" while typing the password logs in
    - Logging in disables inputs and shows loading animation
- **Chat**
    - Hitting "Enter" while typing a message sends a message
    - Hitting "Shift+Enter" while typing a message adds a newline to your message
    - Sending a message disables the chat bar until server responds, after which the chat bar is re-enabled and re-focused

## Issues
- Closes #21 
- Closes #35

### CODE REVIEW

**Review by jsteuver — APPROVED** [review]
Everything looks good. I tested it and it seems to work great.

The only thing I noticed is that using backspace after creating newlines with Shift+Enter does not delete the newline. Obviously not a huge deal, but would be nice to have. Of course I don't know how difficult this would be implement, so it may not even be worth the time it takes to include.

Beyond that, everything is working as intended, so APPROVED.

**Comment by segeeslice** [comment]
> ... The only thing I noticed is that using backspace after creating newlines with Shift+Enter does not delete the newline...

Oof that sounds like a glaring issue to me. Probably a weird semantic change since I know every system ever has discrepencies between `\r` and `\n` and `\r\n`.

I'll definitely look into it before merging

**Comment by segeeslice** [comment]
Just rebased to resolve merge changes; should be the same otherwise, until....

**Comment by segeeslice** [comment]
@jsteuver issue should be fixed, and you should now be able to delete newlines in the chat.

Code change was pretty small and may be self-explanatory, but pretty much when the text was changed and I checked if enter was hit, I was just blindly checking if the last symbol was a newline rather than also verifying we added text. So if multiple newlines were present after each other, then deleting one newline would still result with the new string ending in a newline, so the code was like "oh well enter must have been hit since it still ends with a newline", which was a bit silly.

Good catch for sure; thanks for testing @jsteuver  👍

**Comment by segeeslice** [comment]
Going to go ahead and merge since coming changes depend on some changes here

**Review by jsteuver — COMMENTED** [review]
Nice fix! Changes look good.

**Pull request merged**
