### PR TITLE
Integrate the Intersect page with the server

### LINKED ISSUE #5: Integrate song intersection with server

### PR DESCRIPTION
**Pull request by segeeslice**
## Overview

This PR integrates the `intersection/liked-songs-by-username` endpoint with the front-end for use on the Intersect page. To fit this, some verbiage was changed since the front-end previously took User ID in this area.

In the future, this page will likely change quite a bit and be made more robust since we want additional features (intersecting any two playlists, saving playlists, etc.), but I think it's best to keep the page as originally designed for now. This will allow me to make a **v1.0.0 release** following this PR, since **this is the last of the core logic to be integrated**. Then going forward we can add and modify as needed since we (hopefully) won't have breaking changes between versions anyway.

## Issues

- Closes #5

### CODE REVIEW

**Review by jsteuver — CHANGES_REQUESTED** [review]
Looks really good!

I did notice one thing, however. After loading the intersection for a large number of intersecting liked songs, typing in another username is very sluggish. If you type the name fairly quickly, none of it will show until you've finished typing.

I discovered this by logging into *jake* (jake/mypass) and intersecting with *rob*, which yields a pretty large amount of liked songs. After the page is loaded, I tried typing a different username, *test_user*. Typing this is where I noticed the above issue.

The issue only *seems* to be present after loading a page with a lot of liked songs. Following the same steps as above but flipping the order of the usernames (i.e. intersecting with *test_user* first, followed by *rob*) does not reproduce the issue.

@segeeslice Let me know what you think of this. If the fix for this is too time-consuming (like implementing pagination to reduce the number of songs on the page at once, which would require back-end and front-end work), then we can just leave it as is for now and make a new issue for it or something.

**Comment by segeeslice** [comment]
@jsteuver Oh I noticed that when I made it as well. I think the whole page is re-rendering on each letter type, but i just now realized a possible fix so I'll look into that! Thanks for mentioning it

**Comment by segeeslice** [comment]
@jsteuver Issue is fixed! Thankfully it's this kind of issue is known and expected in React, so the fix is pretty small.

If you're curious, our list of songs now uses a "memoized" version of itself, meaning React won't try to re-render it if the list still contains the same data. So instead of re-rendering the whole page on each typed letter (like it was before), it now only re-renders the songs when the songs themselves change.

**Review by jsteuver — APPROVED** [review]
It feels significantly better. Thanks for taking a look at it!

**Pull request merged**
